name: Flask Docker CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ojiset22
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ojiset22/nusapod-python:latest

      #- name: Trigger Webhook (Server Pull)
      #  run: |
      #    echo "Calling webhook..."
      #    curl -X POST ${{ secrets.WEBHOOK_URL }} -H "Content-Type: application/json" -d '{"event":"update_image","image":"ojiset22/nusapod-python:latest"}'
